test: unify makefile and meson tests
- use meson to execute tests
- reorganize rest of the tests
- collect meson junit xml to gitlab ci/cd

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,78 +1,18 @@
 -include conf.mk
 
-repos	:= repo1 repo2
+.PHONY:
 
-tmproot := /tmp/apk-test
-testroot = $(tmproot)/$(basename $@)
+APK		?= ../src/apk
+LD_LIBRARY_PATH	?= ../src
 
-SUDO	:= sudo
-APK	:= ../src/apk --keys-dir /etc/apk/keys
-
-SYSREPO ?= https://nl.alpinelinux.org/alpine/edge/main
-
-# Absolute path to QEMU user-mode emulation binary to be copied into every
-# $testroot before running test. This is used when running root-tests in
-# emulation using QEMU and binfmt (apk --root uses chroot to run pre/post
-# install scripts).
-QEMU_EMULATOR ?=
-
-LD_LIBRARY_PATH = ../src
-export LD_LIBRARY_PATH SYSREPO
+export APK LD_LIBRARY_PATH
 
 all: tests
 
-$(repos):
-	@echo "Building $@"
-	@rm -f repos.out
-	@cd $@ &&\
-		for i in */APKBUILD; do \
-			( cd $${i%/*} && REPODEST="$$PWD/../.." abuild -r ) \
-				>> ../repos.out 2>&1 || { cat ../repos.out >&2; exit 1; } \
-		done
-
-
-clean:
-	$(SUDO) rm -rf $(addsuffix /*.apk,$(repos)) $(tmproot) *.ok *.out *.stamp
-
-
-repos: repos.stamp
-	
-repos.stamp: $(repos)
-	@touch $@
-	
-
-%.ok: %.sh
-	@echo -n "$<"; \
-		rm -rf "$(testroot)" ;\
-		mkdir -p "$(testroot)"; \
-		if [ -n "$(QEMU_EMULATOR)" ]; then \
-			$(SUDO) install -Dm755 "$(QEMU_EMULATOR)" "$(testroot)$(QEMU_EMULATOR)"; \
-		fi; \
-		if ! APK="$(APK)" ROOT="$(testroot)" SYSREPO="$(SYSREPO)" sh -ex ./$< > $(basename $@).out 2>&1; then\
-			echo " FAIL";\
-			printf '%s\n' "------------- output -------------" >&2;\
-			cat $(basename $@).out >&2;\
-			printf '%s\n' "----------------------------------" >&2;\
-			exit 1;\
-		fi ;\
-		echo " OK" ;\
-		$(SUDO) rm -rf $(testroot); \
-		touch $@
-
-root-tests: repos.stamp
-	@echo "== Testing `$(APK) --version` (tests that require root permission) =="
-	@failed=0; for i in test*.sh; do \
-		rm -f $${i%.sh}.ok ;\
-		$(SUDO) $(MAKE) --no-print-directory $${i%.sh}.ok \
-			SYSREPO=$(SYSREPO) \
-			QEMU_EMULATOR=$(QEMU_EMULATOR) || failed=1; \
-	done; \
-	return $$failed
-
-tests:
+test tests check:
 	@echo "== Testing `$(APK) --version` =="
-	@for i in $(sort $(filter-out test%.sh,$(wildcard *.sh))); do \
-		./$$i || exit 1 ; \
+	@for i in $(wildcard user/*.sh solver.sh); do \
+		./$$i || { echo "FAIL: $$i"; exit 1; }; \
+		echo "OK: $$i"; \
 	done
 
-.PHONY:	$(repos) tests
